openapi: 3.0.0
info:
  title: NVIDIA Isaac Ecosystem API
  description: API for controlling and monitoring NVIDIA Isaac Sim, Isaac ROS, and Nav2 components for humanoid robotics
  version: 1.0.0
  contact:
    name: Isaac Ecosystem Team
    email: isaac-support@nvidia.com

servers:
  - url: http://localhost:8080
    description: Local Isaac Simulation Environment

paths:
  /simulations:
    post:
      summary: Create a new simulation environment
      description: Creates a new Isaac Sim environment with specified parameters
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SimulationConfig'
      responses:
        '201':
          description: Simulation created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Simulation'
        '400':
          description: Invalid simulation configuration
    get:
      summary: List all simulation environments
      responses:
        '200':
          description: List of simulation environments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Simulation'

  /simulations/{id}:
    get:
      summary: Get simulation details
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Simulation details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Simulation'
        '404':
          description: Simulation not found
    put:
      summary: Update simulation configuration
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SimulationConfig'
      responses:
        '200':
          description: Simulation updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Simulation'
        '404':
          description: Simulation not found
    delete:
      summary: Delete a simulation
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Simulation deleted successfully
        '404':
          description: Simulation not found

  /simulations/{id}/start:
    post:
      summary: Start a simulation
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Simulation started successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimulationStatus'
        '404':
          description: Simulation not found

  /simulations/{id}/stop:
    post:
      summary: Stop a simulation
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Simulation stopped successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimulationStatus'
        '404':
          description: Simulation not found

  /robots:
    post:
      summary: Add a humanoid robot to simulation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RobotConfig'
      responses:
        '201':
          description: Robot added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Robot'
    get:
      summary: List all robots in simulation
      responses:
        '200':
          description: List of robots
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Robot'

  /robots/{id}/navigate:
    post:
      summary: Send navigation command to robot
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NavigationGoal'
      responses:
        '200':
          description: Navigation command sent successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NavigationStatus'
        '404':
          description: Robot not found

  /perception:
    get:
      summary: Get perception data from Isaac ROS
      parameters:
        - name: robot_id
          in: query
          required: false
          schema:
            type: string
        - name: sensor_type
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Perception data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PerceptionData'

components:
  schemas:
    Simulation:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the simulation
        name:
          type: string
          description: Name of the simulation
        description:
          type: string
          description: Description of the simulation
        status:
          type: string
          enum: [created, running, paused, stopped]
          description: Current status of the simulation
        created_at:
          type: string
          format: date-time
          description: When the simulation was created
        updated_at:
          type: string
          format: date-time
          description: When the simulation was last updated

    SimulationConfig:
      type: object
      properties:
        name:
          type: string
          description: Name for the simulation
        description:
          type: string
          description: Description of the simulation
        physics_settings:
          $ref: '#/components/schemas/PhysicsSettings'
        lighting_config:
          $ref: '#/components/schemas/LightingConfig'
        environment:
          type: string
          description: Environment to load (USD file path or asset name)

    PhysicsSettings:
      type: object
      properties:
        gravity:
          type: number
          description: Gravity value (m/s^2)
          default: -9.81
        friction:
          type: number
          description: Default friction coefficient
          default: 0.5
        solver_iterations:
          type: integer
          description: Number of solver iterations
          default: 8

    LightingConfig:
      type: object
      properties:
        intensity:
          type: number
          description: Light intensity
          default: 3000
        color:
          type: string
          description: Light color in hex format
          default: "#FFFFFF"
        shadows:
          type: boolean
          description: Whether to enable shadows
          default: true

    Robot:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the robot
        name:
          type: string
          description: Name of the robot
        model_path:
          type: string
          description: Path to the robot USD model
        position:
          $ref: '#/components/schemas/Position'
        orientation:
          $ref: '#/components/schemas/Quaternion'
        status:
          type: string
          enum: [idle, moving, navigating, paused]
          description: Current status of the robot

    RobotConfig:
      type: object
      properties:
        name:
          type: string
          description: Name for the robot
        model_path:
          type: string
          description: Path to the robot USD model
        position:
          $ref: '#/components/schemas/Position'
        orientation:
          $ref: '#/components/schemas/Quaternion'

    Position:
      type: object
      properties:
        x:
          type: number
          description: X coordinate
        y:
          type: number
          description: Y coordinate
        z:
          type: number
          description: Z coordinate

    Quaternion:
      type: object
      properties:
        x:
          type: number
          description: X component
        y:
          type: number
          description: Y component
        z:
          type: number
          description: Z component
        w:
          type: number
          description: W component

    NavigationGoal:
      type: object
      properties:
        target_position:
          $ref: '#/components/schemas/Position'
        frame:
          type: string
          description: Coordinate frame for the target
          default: "map"
        tolerance:
          type: number
          description: Tolerance for reaching the goal (meters)
          default: 0.25

    NavigationStatus:
      type: object
      properties:
        status:
          type: string
          enum: [pending, active, succeeded, failed, canceled]
        current_position:
          $ref: '#/components/schemas/Position'
        remaining_distance:
          type: number
          description: Distance remaining to goal (meters)
        path:
          type: array
          items:
            $ref: '#/components/schemas/Position'
          description: Planned path to goal

    PerceptionData:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
          description: When the data was captured
        robot_id:
          type: string
          description: ID of the robot that captured the data
        sensor_type:
          type: string
          enum: [camera, lidar, imu, depth, rgb]
          description: Type of sensor
        data:
          type: object
          description: Sensor-specific data payload

    SimulationStatus:
      type: object
      properties:
        status:
          type: string
          enum: [running, paused, stopped]
        elapsed_time:
          type: number
          description: Time elapsed in simulation (seconds)
        real_time_factor:
          type: number
          description: Real-time factor (simulation time / real time)